apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: demo
  name: demo-ingress
spec:
  rules:
  - host: my.demo.com
    http:
      paths:
      - path: /hello
        backend:
          serviceName: hello-service
          servicePort: 80
      - path: /bye
        backend:
          serviceName: bye-service
          servicePort: 80
      - path: /auth
        backend:
          serviceName: auth-service
          servicePort: 80