---

apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Chart.Name }}
  name: {{ .Values.app_name }}-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app_name }}
  ports:
  - name: {{ .Values.app_name }}
    protocol: TCP
    port: 80
    targetPort: {{ .Values.container_port }}
