---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: auth-deployment
  namespace: demo
  labels:
    app: auth
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2        
      maxUnavailable: 1
  minReadySeconds: 10
  progressDeadlineSeconds: 120
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: sirius226/eup-demo-auth:1.0
        env:
        - name: MY_SECRET
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: secret
        - name: MY_ENV
          valueFrom:
            configMapKeyRef:
              name: demo-config
              key: env
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 200m
      terminationGracePeriodSeconds: 30
