---

apiVersion: v1
kind: Service
metadata:
  namespace: demo
  name: bye-service
spec:
  type: ClusterIP
  selector:
    app: bye
  ports:
  - name: bye
    protocol: TCP
    port: 80
    targetPort: 8080