---

apiVersion: v1
kind: Service
metadata:
  namespace: demo
  name: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
  - name: auth
    protocol: TCP
    port: 80
    targetPort: 8080