---

apiVersion: v1
kind: Service
metadata:
  namespace: demo
  name: hello-service
spec:
  type: ClusterIP
  selector:
    app: hello
  ports:
  - name: hello
    protocol: TCP
    port: 80
    targetPort: 8080
