---

apiVersion: v1
kind: Service
metadata:
  namespace: demo
  name: name-service
spec:
  type: ClusterIP
  selector:
    app: name
  ports:
  - name: name
    protocol: TCP
    port: 80
    targetPort: 8080
